luet/templates/upd-extra-pkgs-pipeline.tmpl: Integrate new tasks

diff --git a/luet/templates/upd-extra-pkgs-pipeline.tmpl b/luet/templates/upd-extra-pkgs-pipeline.tmpl
--- a/luet/templates/upd-extra-pkgs-pipeline.tmpl
+++ b/luet/templates/upd-extra-pkgs-pipeline.tmpl
@@ -39,8 +39,8 @@
 #                 commits the upgraded package.
 #
 #              f) run a task that execute the build of the packages:
-#                    - seed/macaroni-stage3
-#                    - seed/macaroni-base
+#                    - seed/macaroni-funtoo-stage
+#                    - seed/macaroni-funtoo-base
 #                 with the --push option in the luet command
 #                 that permits to sync the generated docker image
 #                 in the internal docker registry.
@@ -193,6 +193,11 @@ tasks:
       docker login -u ${registry_user} -p ${registry_pass}
       docker-registry1.mottainai.local:5000
 
+    {{- if eq .push_images "true" }}
+    - export BUILD_ARGS="--no-spinner --emoji=true --color=false  --live-output --only-target-package  --pull --push"
+    {{- else }}
+    - export BUILD_ARGS="--no-spinner --emoji=true --color=false  --live-output --only-target-package  --pull"
+    {{- end }}
     {{- if eq .enable_docker_host "true" }}
     - echo "Using DOCKER_HOST ${DOCKER_HOST}..."
     {{- else }}
@@ -211,17 +216,12 @@ tasks:
     - "REPO_CACHE=docker-registry1.mottainai.local:5000/luet-{{ .namespace }}-tree"
     - "REPO={{ .repo }}"
     - "REPO_BRANCH={{ .branch }}"
-    {{- if eq .push_images "true" }}
-    - "BUILD_ARGS=--no-spinner --emoji=true --color=false  --live-output --only-target-package  --pull --push"
-    {{- else }}
-    - "BUILD_ARGS=--no-spinner --emoji=true --color=false  --live-output --only-target-package  --pull"
-    {{- end }}
     - LUET_SYSTEM__TMPDIR_BASE=/luettmp
     - LUET_YES=true
     {{- if eq .enable_docker_host "true" }}
     - DOCKER_HOST=docker-overlay2.mottainai.local:2376
     {{- end }}
-    - "PACKAGES={{ .pkgs }}"
+    - "PACKAGES=seed/funtoo-kits toolchain/meta-repo"
     image: macaroni/funtoo-builder
     artefact_path: /artefacts
     type: lxd
@@ -270,7 +270,7 @@ tasks:
     publish_mode: append
     tag_namespace: "{{ .namespace }}"
 
-# Step c -------------------- Purge CDN repo files
+# Step C and D -------------------- Purge CDN repo files
 
   purge-cdn-files:
     name: "Purge files from CDN77 resource ({{ .namespace }})"
@@ -297,7 +297,144 @@ tasks:
     environment:
     - "NAMESPACE={{ .namespace }}"
 
+# Step F -------------------- Run luet-portage-converter to bump new packages.
   luet-portage-convert:
+    name: "Luet Portage Converter <{{ .namespace }}> - ({{ dateInZone "2006-01-02T15:04:05.000Z" (now) "UTC" }})"
+    image: macaroni/funtoo-metatools
+    storage: "geaaru-github,mcli"
+    storage_path: /storage
+    artefact_path: /artefacts
+    namespace: "{{ .namespace }}-reposcan"
+    type: lxd
+    environment:
+    - LUET_SYSTEM__TMPDIR_BASE=/luettmp
+    - LUET_YES=true
+    - "KITS_2UPGRADE={{ .kits2upgrade }}"
+    - "REPO_BRANCH={{ .repobranch }}"
+    - "REPO={{ .repossh }}"
+    - "NAMESPACE={{ .namespace }}"
+
+    script:
+    - >-
+      luet repo update &&
+      luet install utils/jq utils/yq net-misc/openssh
+      dev-util/mottainai-cli sys-devel/make
+      extension/luet-portage-converter
+      &&
+      luet reinstall virtual/base &&
+      luet cleanup &&
+      env-update &&
+      ldconfig
+
+    # Setup Mottainai stuff
+    - export HOME=/root && mkdir -p /root/.config/
+    - /bin/bash /storage/setup-mcli.sh
+
+    # Setup git ssh key
+    - sh /storage/setup-ssh.sh
+    - sh /storage/setup-git.sh
+
+    - >-
+      git clone ${REPO} -b ${REPO_BRANCH} /luet-repo &&
+      mkdir /luet-repo/kit_cache -p &&
+      cp -vf /artefacts/* /luet-repo/kit_cache/ &&
+      rm -rf /artefacts/*
+
+    - >-
+      git clone https://code.funtoo.org/bitbucket/scm/mos/macaroni-tasks.git
+      /macaroni-tasks &&
+      cd /macaroni-tasks &&
+      MOTTAINAI_CLI_PROFILE=funtoo
+      LUET_REPOSITORY=/luet-repo
+      make luet-pc
+    - >-
+      cd /luet-repo &&
+      git status &&
+      BUMPER_DIR=./packages/atoms-extra/ sh scripts/bumper.sh &&
+      eval 'git push || true' ;
+
+# Step G -------------------- Build seed/macaroni-funtoo-stage, seed/macaroni-funtoo-base packages.
+  build-seeds-base:
+    name: "luet - seed/macaroni-funtoo-stage, seed/macaroni-funtoo-base <{{ .namespace }}> - {{ dateInZone "2006-01-02T15:04:05.000Z" (now) "UTC" }}"
+    storage: docker-certs
+    storage_path: /storage
+    script:
+    - source /storage/prepare-luet.sh
+    - >-
+      luet repo update &&
+      luet upgrade &&
+      luet cleanup --purge-repos
+    - >-
+      docker login -u ${registry_user} -p ${registry_pass}
+      docker-registry1.mottainai.local:5000
+
+    {{- if eq .push_images "true" }}
+    - export BUILD_ARGS="--no-spinner --emoji=true --color=false  --live-output --only-target-package  --pull --push"
+    {{- else }}
+    - export BUILD_ARGS="--no-spinner --emoji=true --color=false  --live-output --only-target-package  --pull"
+    {{- end }}
+    {{- if eq .enable_docker_host "true" }}
+    - echo "Using DOCKER_HOST ${DOCKER_HOST}..."
+    {{- else }}
+    - /etc/init.d/docker start
+    {{- end }}
+    - git clone ${REPO} -b ${REPO_BRANCH} /build
+    - cd /build && make rebuild
+    - >-
+      rm -rf build/build &&
+      cp -v build/* /artefacts/
+    environment:
+    {{- if eq .enable_buildkit "true" }}
+    - "BUILDKIT_PROGRESS=plain"
+    - "DOCKER_BUILDKIT=1"
+    {{- end }}
+    - "REPO_CACHE=docker-registry1.mottainai.local:5000/luet-{{ .namespace }}-tree"
+    - "REPO={{ .repo }}"
+    - "REPO_BRANCH={{ .branch }}"
+    - LUET_SYSTEM__TMPDIR_BASE=/luettmp
+    - LUET_YES=true
+    {{- if eq .enable_docker_host "true" }}
+    - DOCKER_HOST=docker-overlay2.mottainai.local:2376
+    {{- end }}
+    - "PACKAGES=seed/macaroni-funtoo-stage seed/macaroni-funtoo-base"
+    image: macaroni/funtoo-builder
+    artefact_path: /artefacts
+    type: lxd
+    #retry: "2"
+    publish_mode: append
+    tag_namespace: "{{ .namespace }}"
+
+# Step G -------------------- Run tasks that create build pipeline for all new packages.
+  start-build-task:
+    name: "Start Build pipeline <{{ .namespace }}> - {{ dateInZone "2006-01-02T15:04:05.000Z" (now) "UTC" }}"
+    storage: "mcli"
+    storage_path: /storage
+    script:
+    - export HOME=/root && mkdir -p /root/.config/
+    - /bin/bash /storage/setup-mcli.sh
+    - >-
+      export MOTTAINAI_CLI_PROFILE=funtoo
+    - >-
+      luet repo update &&
+      luet i -y system/luet-devkit &&
+      luet cleanup --purge-repos
+    - >-
+      git clone ${REPO} -b ${REPO_BRANCH} /repo &&
+      git clone ${REPO_MTASKS} /macaroni-tasks
+    - >-
+      cd /macaroni-tasks &&
+      ls -l /repo &&
+      export LUET_REPOSITORY=/repo &&
+      make build-pipeline
+    environment:
+    - "NAMESPACE={{ .namespace }}"
+    - "REPO={{ .repo }}"
+    - "REPO_BRANCH={{ .branch }}"
+    - "REPO_MTASKS=https://code.funtoo.org/bitbucket/scm/mos/macaroni-tasks.git"
+    image: macaroni/funtoo-builder
+    artefact_path: /artefacts
+    type: lxd
+#retry: "2"
 
 
-# vim: set filetype=yaml
+# vim: filetype=yaml
