Add new targets and new pipelines

diff --git a/make/start-upgrade-seed-pipeline b/make/start-upgrade-seed-pipeline
--- a/make/start-upgrade-seed-pipeline
+++ b/make/start-upgrade-seed-pipeline
@@ -11,24 +11,38 @@ FIRE_TASK=${FIRE_TASK:-0}
 ENABLE_DOCKER_HOST=${ENABLE_DOCKER_HOST:-true}
 ENABLE_BUILDKIT=${ENABLE_BUILDKIT:-false}
 PUSH_IMAGES=${PUSH_IMAGES:-false}
+SEED=${SEED:-}
+REPO_DIR="${REPO_DIR:-}"
+kits_map="${KITS_MAPFILE:-${REPO_DIR}/portage-converter/kits-specs-map.yaml}"
+BUMP_SEED="${BUMP_SEED:-false}"
 
 main () {
 
   if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
     echo "Missng MOTTAINAI_CLI_PROFILE env variable"
-    exit 1
+    return 1
   fi
 
   if [ -z "${NAMESPACE}" ] ; then
     echo "Missing NAMESPACE env variable."
     echo "Normally this variable is equal to repository name."
-    exit 1
+    return 1
   fi
 
   isvalid=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | length")
   if [ "${isvalid}" == "0" ] ; then
     echo "Selected repository not defined on luet-repo.values file."
-    exit 1
+    return 1
+  fi
+
+  if [ -z "${SEED}" ] ; then
+    echo "Missing SEED env variable."
+    return 1
+  fi
+
+  if [ -z "${REPO_DIR}" ] ; then
+    echo "Missing REPO_DIR env variable."
+    return 1
   fi
 
   repo=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .http_repo" -r)
@@ -36,8 +50,13 @@ main () {
   repo_ssh=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .ssh_repo" -r)
   local upgrade_kit=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .upgrade_kit" -r)
   local kits2upgrade=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .kits2upgrade | join(\" \")" -r)
-  local seeds2bump=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .seeds2bump | join(\" \")" -r)
   local lpc_extra_ns=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .lpc_extra_ns | join(\",\")" -r)
+  local seed=$(yq r ${kits_map} seeds -j | jq ".[] | select(.name==\"${SEED}\")" -r -c)
+
+  if [ -z "${seed}" ] ; then
+    echo "Invalid seed selected"
+    return 1
+  fi
 
   if [ "${upgrade_kit}" != "true" ] ; then
     echo "The selected repository is without upgrade_kit enable."
@@ -49,14 +68,15 @@ main () {
     return 1
   fi
 
-  if [ -z "${seeds2bump}" ] ; then
-    echo "No seed to bump for repo ${repo}!"
+  if [ -z "${seed}" ] ; then
+    echo "Invalid seed ${SEED} selected."
     return 1
   fi
 
   echo "
 Kits 2 upgrade: ${kits2upgrade}
 Extra Kits Namespace: ${lpc_extra_ns}
+Seed: seed/${SEED}
 "
 
   local opts=""
@@ -68,7 +88,7 @@ Extra Kits Namespace: ${lpc_extra_ns}
     opts="${opts} -s extrans=${lpc_extra_ns}"
   fi
 
-  mottainai-cli task compile ${luet_dir}/templates/upd-extra-pkgs-pipeline.tmpl \
+  mottainai-cli task compile ${luet_dir}/templates/upd-extra-pkgs-seed-pipeline.tmpl \
     -s namespace="${NAMESPACE}" ${opts} \
     -s repohttp="${repo}" \
     -s repobranch="${repo_branch}" \
@@ -76,15 +96,15 @@ Extra Kits Namespace: ${lpc_extra_ns}
     -s kits2upgrade="${kits2upgrade}" \
     -s enable_docker_host="${ENABLE_DOCKER_HOST}" \
     -s enable_buildkit="${ENABLE_BUILDKIT}" \
-    -s seeds2bump="${seeds2bump}" \
-    -o /tmp/upd-extra-pkgs-pipeline.yaml || return 1
+    -s seed="${SEED}" \
+    -o /tmp/upd-extra-pkgs-seed-pipeline.yaml || return 1
 
   if [ "${FIRE_TASK}" = "1" ] ; then
-    mottainai-cli pipeline create --yaml /tmp/upd-extra-pkgs-pipeline.yaml || return 1
+    mottainai-cli pipeline create --yaml /tmp/upd-extra-pkgs-seed-pipeline.yaml || return 1
   fi
 
   if [ -z "${SKIP_CLEAN}" ] ; then
-    rm /tmp/upd-extra-pkgs-pipeline.yaml
+    rm /tmp/upd-extra-pkgs-seed-pipeline.yaml
   fi
 
   return 0
