make/start-upgrade-seed-pipeline: Add support to tree v2

diff --git a/make/start-upgrade-seed-pipeline b/make/start-upgrade-seed-pipeline
--- a/make/start-upgrade-seed-pipeline
+++ b/make/start-upgrade-seed-pipeline
@@ -48,6 +48,7 @@ main () {
   repo=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .http_repo" -r)
   repo_branch=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .branch" -r)
   repo_ssh=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .ssh_repo" -r)
+  tree_version=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .tree_version" -r)
   local upgrade_kit=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .upgrade_kit" -r)
   local kits2upgrade=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .kits2upgrade | join(\" \")" -r)
   local lpc_extra_ns=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .lpc_extra_ns | join(\",\")" -r)
@@ -73,10 +74,16 @@ main () {
     return 1
   fi
 
+  if [ -z "${tree_version}" ] ; then
+    echo "Missing tree version for repo ${repo}!"
+    return 1
+  fi
+
   echo "
 Kits 2 upgrade: ${kits2upgrade}
 Extra Kits Namespace: ${lpc_extra_ns}
 Seed: seed/${SEED}
+Tree Version: ${tree_version}
 "
 
   local opts=""
@@ -88,17 +95,37 @@ Seed: seed/${SEED}
     opts="${opts} -s extrans=${lpc_extra_ns}"
   fi
 
-  mottainai-cli task compile ${luet_dir}/templates/upd-extra-pkgs-seed-pipeline.tmpl \
-    -s namespace="${NAMESPACE}" ${opts} \
-    -s repohttp="${repo}" \
-    -s repobranch="${repo_branch}" \
-    -s repossh="${repo_ssh}" \
-    -s kits2upgrade="${kits2upgrade}" \
-    -s enable_docker_host="${ENABLE_DOCKER_HOST}" \
-    -s enable_buildkit="${ENABLE_BUILDKIT}" \
-    -s seed="${SEED}" \
-    -s bumpseed="${BUMP_SEED}" \
-    -o /tmp/upd-extra-pkgs-seed-pipeline.yaml || return 1
+  # Create pipeline
+  if [ "${TREE_VERSION}" = "v2" ] ; then
+
+    mottainai-cli task compile ${luet_dir}/templates/upd-extra-pkgs-seed-pipeline.tmpl \
+      -s namespace="${NAMESPACE}" ${opts} \
+      -s repohttp="${repo}" \
+      -s repobranch="${repo_branch}" \
+      -s repossh="${repo_ssh}" \
+      -s kits2upgrade="${kits2upgrade}" \
+      -s enable_docker_host="${ENABLE_DOCKER_HOST}" \
+      -s enable_buildkit="${ENABLE_BUILDKIT}" \
+      -s seed="${SEED}" \
+      -s bumpseed="${BUMP_SEED}" \
+      -s treeversion="${tree_version}" \
+      -o /tmp/upd-extra-pkgs-seed-pipeline.yaml || return 1
+
+  else
+
+    mottainai-cli task compile ${luet_dir}/templates/upd-extra-pkgs-seed-pipeline.tmpl \
+      -s namespace="${NAMESPACE}" ${opts} \
+      -s repohttp="${repo}" \
+      -s repobranch="${repo_branch}" \
+      -s repossh="${repo_ssh}" \
+      -s kits2upgrade="${kits2upgrade}" \
+      -s enable_docker_host="${ENABLE_DOCKER_HOST}" \
+      -s enable_buildkit="${ENABLE_BUILDKIT}" \
+      -s seed="${SEED}" \
+      -s bumpseed="${BUMP_SEED}" \
+      -s treeversion="${tree_version}" \
+      -o /tmp/upd-extra-pkgs-seed-pipelinev2.yaml || return 1
+  fi
 
   if [ "${FIRE_TASK}" = "1" ] ; then
     mottainai-cli pipeline create --yaml /tmp/upd-extra-pkgs-seed-pipeline.yaml || return 1
