Ensure to use right namespace for tagging

diff --git a/make/tag4test-pipeline b/make/tag4test-pipeline
--- a/make/tag4test-pipeline
+++ b/make/tag4test-pipeline
@@ -30,6 +30,13 @@ main () {
 
   repo=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .http_repo" -r)
   repo_branch=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .branch" -r)
+  repo4test=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .repo4test_tag" -r)
+
+
+  if [ "${repo4test}" != "true" ] ; then
+    echo "Selected repository invalid for tagging. See repo4test_tag field."
+    exit 1
+  fi
 
   echo "
 Creating pipeline for tagging ${NAMESPACE}-dev to ${NAMESPACE}...
diff --git a/make/tag4testing b/make/tag4testing
--- a/make/tag4testing
+++ b/make/tag4testing
@@ -22,9 +22,16 @@ main () {
     exit 1
   fi
 
+  repo4test=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .repo4test_tag" -r)
   isvalid=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | length")
+
   if [ "${isvalid}" == "0" ] ; then
     echo "Selected repository not defined on luet-repo.values file."
+    exit 1
+  fi
+
+  if [ "${repo4test}" != "true" ] ; then
+    echo "Selected repository invalid for tagging. See repo4test_tag field."
     exit 1
   fi
 
